{% set name = "ODM" %}
{% set version = "master" %}
{% set sha256 = "e9931964a9c483e7e3a9185deb4bf62b91642fb27a2a94b99ac057216ff9db85" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/OpenDroneMap/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - ODM.patch

build:
  number: 1

requirements:
  build:
    # - {{ compiler('c') }}
    # - {{ compiler('cxx') }}
    - cmake
    # - ninja

  host:
    - exiv2 {{ exiv2 }}
    - eigen {{ eigen }}
    - pangolin {{ pangolin }}
    - opencv {{ opencv }}
    - orb_slam2 {{ orb_slam2 }}
    - flann {{ flann }}
    - pcl {{ pcl }}
    - vtk {{ vtk }}
    - proj4
    - boost
    - glew

  run:
    - ecto {{ ecto }}
    - laszip {{ laszip }}
    - exiv2 {{ exiv2 }}
    - pangolin {{ pangolin }}
    - opencv {{ opencv }}
    - orb_slam2 {{ orb_slam2 }}
    - opensfm {{ opensfm }}
    - flann {{ flann }}
    - pcl {{ pcl }}
    - vtk {{ vtk }}
    - geotiff {{ geotiff }}
    - pdal {{ pdal }}
    - mve {{ mve }}
    - smvs {{ smvs }}
    - mvstexturing {{ mvstexturing }}
    - poissonrecon {{ poissonrecon }}
    - dem2mesh {{ dem2mesh }}
    - dem2points {{ dem2points }}
    - proj4
    - boost
    - glew
    - opengv {{ opengv }}
    - gdal {{ gdal }}

about:
  home: https://www.opendronemap.org
  summary: A command line toolkit to generate maps, point clouds, 3D models and DEMs from drone, balloon or kite images.
  license: GPL 3.0

extra:
  recipe-maintainers:
  - v-turin
