{% set name = "ODM" %}
{% set version = "v0.5.0" %}
{% set commit = "cd34d9d16bf048cd726e2e7a9f36311cb21f7a52" %}
{% set sha256 = "38bb96a08d1fafa7a87057778a8acc90625d1a56ce56769b9243c80a2630bddd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/OpenDroneMap/{{ name }}/archive/{{ commit }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - ODM.patch

build:
  number: 1

requirements:
  build:
    # - {{ compiler('c') }}
    # - {{ compiler('cxx') }}
    - cmake
    # - ninja

  host:
    - exiv2 {{ exiv2 }}
    - eigen {{ eigen }}
    - pangolin {{ pangolin }}
    - opencv {{ opencv }}
    - orb_slam2 {{ orb_slam2 }}
    - flann {{ flann }}
    - pcl {{ pcl }}
    - vtk {{ vtk }}
    - proj4
    - boost
    - glew

  run:
    - ecto {{ ecto }}
    - laszip {{ laszip }}
    - exiv2 {{ exiv2 }}
    - pangolin {{ pangolin }}
    - opencv {{ opencv }}
    - orb_slam2 {{ orb_slam2 }}
    - opensfm {{ opensfm }}
    - flann {{ flann }}
    - pcl {{ pcl }}
    - vtk {{ vtk }}
    - geotiff {{ geotiff }}
    - pdal {{ pdal }}
    - mve {{ mve }}
    - smvs {{ smvs }}
    - mvstexturing {{ mvstexturing }}
    - poissonrecon {{ poissonrecon }}
    - dem2mesh {{ dem2mesh }}
    - dem2points {{ dem2points }}
    - proj4
    - boost
    - glew
    - opengv {{ opengv }}
    - gdal {{ gdal }}

about:
  home: https://www.opendronemap.org
  summary: A command line toolkit to generate maps, point clouds, 3D models and DEMs from drone, balloon or kite images.
  license: GPL 3.0

extra:
  recipe-maintainers:
  - v-turin
